### ISSUE TITLE
01-Create page for my favourite dishes 

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#1]
## Value proposition

**As a** user,
**I want to** have a form in order to save all the names of dishes which I usually cook at home,
**so that** I can have an overview about my favorite home-cooking dishes.

## Description

<img alt="01-UserStory" src="https://user-images.githubusercontent.com/104725727/176434998-b2866fc9-4ccc-45e9-97c2-ba18d86d60e8.png" width=320px>

## Acceptance criteria

- [x] heading stays on top of the page
- [x] After click submit button, dish's name display under "My favorite dishes"
- [x] Dishes are added to the end of the list
- [x] Whitespace is trimmed

## Complexity

Medium

## Tasks

- [x] Create branch
- [x] Add base styles
- [x] Add input for the names of the dishes
- [x] Add button for submit
- [x] set up stories for form
- [x] write specs for form
- [x] Implement form elements
- [x] Update state logic in app

**Comment by PReichetanz** [comment]
Hi Quan,
this is a good start!

Things which came to my mind:
- You can use this as first story, but where is the data displayed after submit? Please add a scribble and adjust your story.
- Otherwise, you could use this as second story and write a first one "Display favourite cooking recipes" or similar.

**Comment by ahohnsen** [comment]
Hey Quan,

I have a few questions:
- How should the user type in the ingredients as usually there is more than one ingredient for a recipe? Should the ingredients be separated by a space, comma or something else? It would be useful to let the user know how to enter the data and as well you can mention this in the acceptance criteria.
- Is there a limitation for the input fields or can I enter an endless amount of characters?
- Can I only see the recipe names in the list or also the ingredients? As in your scribble it looks like only the names of the recipe will be shown.

**Comment by mbosselmann** [comment]
Hi Quan,
good work 👍 , but I think there are some parts of your story which you should think about before moving further:

**Value proposition**
- currently your form does not save all the information about the dishes but the name of the dishes you usually cook at home and I think that is enough for your first user story. But another user story should maybe cover this value proosition
- A question: "so that I can have an overview." I would explain which overview you mean Maybe "so that I can have an overview about my favourite dishes"

**Description**
- your scribble shoes an input field for ingredients, but the values are nowhere displayed afterwards. I think currently this input field is not necessary for the implementation of this user story

**Acceptance criteria**
- "Whitespace is trimmed" is more of a task I think

I hope my remarks are helpful! Fell free to ask me if you have questions. :)

**Comment by QuanXuuu** [comment]
**Value proposition**
> 
>     * currently your form does not save all the information about the dishes but the name of the dishes you usually cook at home and I think that is enough for your first user story. But another user story should maybe cover this value proosition
> 
>     * A question: "so that I can have an overview." I would explain which overview you mean Maybe "so that I can have an overview about my favourite dishes"
> 
> 
> **Description**
> 
>     * your scribble shoes an input field for ingredients, but the values are nowhere displayed afterwards. I think currently this input field is not necessary for the implementation of this user story
> 

Thank you for checking my user story. I made the following changes according to your advice:
- Change the Value proposition to make it more clear;
- Delete the "Add Ingredients Input", but will put this feature in the next user story

**Comment by mbosselmann** [comment]
Hi Quan,
great! 👍 Looks good to me!

Happy hacking! :)
