### ISSUE TITLE
05 - delete button

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#11]
## Value proposition

**As a** user,
**I want to** have a delete button,
**so that** I can manage the recipes.

## Description

<img width="762" alt="Screenshot 2022-07-11 at 13 41 09" src="https://user-images.githubusercontent.com/104725727/178256516-6665edc2-2f81-45f3-99a5-e3b6676e2df5.png">

## Acceptance criteria

- [ ] Each detailed recipe has a delete button at the bottom
- [ ] After click the delete button at the bottom , will prompt a double-check box
- [ ] After click cancel button, the delete process will be stopped
- [ ] After click delete button in the box, recipe will finally be deleted

## Complexity

Medium 

## Tasks

- [ ] Create branch
- [ ] Create delete button
- [ ] Create prompt for double check
- [ ] Add style to component
