### ISSUE TITLE
06-Edit Page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#14]
## Value proposition

**As a** user,
**I want to** have edit function,
**so that** I can change and save the information of my recipes.

## Description

<img width="646" alt="Screenshot 2022-07-14 at 21 41 44" src="https://user-images.githubusercontent.com/104725727/179069897-c48859a9-d7ee-4f71-a8cd-500a4254b152.png">

## Acceptance criteria

- [x] After click edit button, will be navigated to edit page
- [x] All information on edit page can rewrite and save

## Complexity

Large

## Tasks

- [x] Create branch
- [x] Create Edit button
- [x] Create Edit page
- [x] Update state logic in App
