### ISSUE TITLE
Create page for dining-out

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#2]
## Value proposition

**As a** user,
**I want to** have a form in order to save my favorite restaurants,
**so that** I don't need to remember all the information about the restaurants.

## Description
<img alt="Create-DO" src="https://user-images.githubusercontent.com/104725727/175277904-c6e7f181-8fcc-415f-8756-f39217e41d1f.png" width=320px>

## Acceptance criteria

- [ ] heading stays on top of the page
- [ ] Button stays at the bottom of the page
- [ ] Inputs can scrolling y

## Complexity

Medium 

## Tasks

- [ ] Create branch
- [ ] Add inputs for restaurants information
- [ ] Add button for submit
- [ ] set up storybook for the form element
- [ ] write specs for the form element

**Comment by ahohnsen** [comment]
Hey Quan,

I am not sure if this is going to be your second user story. 🤔 If so, I cannot see how this page is connected to the one you created in your first user story. You could add a simple link to switch between the two pages. You should then also display this in your scribble and mention it in the acceptance criteria.

As well, it would be good to know if any of the input fields are required in order to submit the form. If so this should be mentioned in the acceptance criteria and also be visible to the user for a better user experience.

When you update this user story, please have a look at your first one. We can apply the same changes here: The data which is entered by the user, should be displayed somewhere. This should be also shown in your scribble and mentioned in your acceptance criteria. If you have any questions regarding my suggestions, please do not hesitate to ask :)
