### ISSUE TITLE
07 - Landing page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#20]
## Value proposition

**As a** user,
**I want to** have a landing page
**so that** I start navigating from there.

## Description
<img width="290" alt="Screenshot 2022-07-22 at 22 03 51" src="https://user-images.githubusercontent.com/104725727/180518796-e1e4d8e8-a55e-437f-af94-5ba4aeb177a6.png"

## Acceptance criteria

- [ ] After click Arrow button will navigate to homepage(show all recipes)
- [ ] App title stay in the middle

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] Implement redirect button
- [ ] Add Header
- [ ] Add styling and basic design
- [ ] Add photo
