### ISSUE TITLE
07 - Landing page

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#21]
## Value proposition

**As a** user,
**I want to** have a landing page
**so that** I start navigating from there.

## Description
<img width="290" alt="Screenshot 2022-07-22 at 22 03 51" src="https://user-images.githubusercontent.com/104725727/180519412-60ebe579-127b-4e46-b3ac-ec9487090c51.png">

## Acceptance criteria

- [x] After click Arrow button will navigate to homepage(show all recipes)
- [x] App title stay in the middle

## Complexity

Small

## Tasks

- [x] Create branch
- [x] Implement redirect button
- [x] Add Header
- [x] Add styling and basic design
- [x] Add photo
