### ISSUE TITLE
Display and styling my Favorite Recipes

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#3]
## Value proposition

**As a** user,
**I want to** have a separate page to show all the dishes I saved,
**so that** I can have a better overview.

## Description

<img alt="Display-HC" src="https://user-images.githubusercontent.com/104725727/175316929-27bb3b0e-dd07-48a8-b3b4-ef501c872990.png" width=320px>

## Acceptance criteria
- [ ] Heading stays on the top of the page
- [ ] Each dish has a card
- [ ] Page is scrollable

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Styling the cards
- [ ] Setup stories for the cards
- [ ] Write specs for the cards

**Comment by QuanXuuu** [comment]
I have added a new "02-user story", this feature will be used as the "04 or 05-user story" at a later stage.
