### ISSUE TITLE
02-Add Ingredients of my favorite dishes

### ISSUE THREAD

**Issue by QuanXuuu** [QuanXuuu/Capstone-project#5]
## Value proposition

**As a** user,
**I want to** have a form where I can save all the ingredients info of my favorite dishes,
**so that** I don't need to remember all the information.

## Description

<img width="624" alt="02-UserStory" src="https://user-images.githubusercontent.com/104725727/176203941-3e921a6a-9096-4c7a-8a63-bdd75f50918a.png" width=500px>

## Acceptance criteria

- [x] Click dish's name on 'RecipesList Page', will navigate to 'RecipeDetails Page'
- [x] Heading stays on top of the page
- [x] Click "Add" button, dish's name display under "My Ingredients"
- [x] Ingredients are added to the end of the list
- [x] Whitespace is trimmed
- [x] Click "Back" button, will navigate back to 'RecipesList Page'

## Complexity

Medium 

## Tasks

- [x] Create branch
- [x] Add input for the ingredients of the dishes
- [x] Add button for "Add"
- [x] Add button for "Back"
- [x] Implement form elements
- [x] Update state logic in app
